### PR TITLE
ISSUE #105: support unions of a single type

### PR DESCRIPTION
**Pull request by dbieber**
#105 
Adds support in SchemaConverters for unions of a single type.

### CODE REVIEW

**Comment by vlyubin** [comment]
Hey @dbieber - this is great! Can you extend one of the unit tests to include a union of a single type so that we hit this code path, and address a comment - then we'll merge it.

**Comment by dbieber** [comment]
Will do.

**Comment by dbieber** [comment]
At first I tried extending the existing test that uses test.avro, but I was having trouble modifying test.avro. The issue I hit was that the tools I was using couldn't read test.avro since 'record' is a reserved name. Rather than dive into this issue, I created a new test instead (see diff).

**Comment by dbieber** [comment]
Copying the PR for issue 96, I bumped spark to 1.5.2 from 1.5.0rc2 in order to make travis happy.

**Comment by JoshRosen** [comment]
If you're going to bump from 1.5.0-RC2, I think you should bump to 1.5.0 and remove the old staging repo resolvre from the build.

I'll let @vlyubin do the signoff on the code changes and I'll push a separate commit myself right now in order to make the build / Travis changes (so this PR can stay tiny).

**Comment by JoshRosen** [comment]
I'm splitting the build changes into a separate PR, #112.

**Comment by vlyubin** [comment]
Looks good, merging. Thanks!

**Comment by JoshRosen** [comment]
@vlyubin, next time can you use the merge script?  `./dev/merge-pr.py`.

**Comment by vlyubin** [comment]
@JoshRosen, yup, sorry about that. I'll use it next time.

**Comment by dbieber** [comment]
Cheers!
Thanks to both of you for support in getting this pr in quickishly.

**Pull request merged**
