### PR TITLE
Upgrade to spark 2.1.0

### LINKED ISSUE #205: Upgrade to spark 2.1.x
The FileFormat APIs are not stable yet so we need a new version of spark-avro for spark 2.1.x

Using spark-avro 3.1.0 with spark 2.1.0 gives:
```
java.lang.AbstractMethodError
    at org.apache.spark.sql.execution.datasources.FileFormatWriter$SingleDirectoryWriteTask.<init>(FileFormatWriter.scala:232)
    at org.apache.spark.sql.execution.datasources.FileFormatWriter$.org$apache$spark$sql$execution$datasources$FileFormatWriter$$executeTask(FileFormatWriter.scala:182)
    at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:129)
    at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1$$anonfun$3.apply(FileFormatWriter.scala:128)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
    at org.apache.spark.scheduler.Task.run(Task.scala:99)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by koertkuipers**
Closes #205 

I am not entirely sure why i had to make changes in getDefaultWorkFile. Without these changes one extra (and unnecessary) layer of subdirectories was created upon writing, which meant no avro files were found upon reading.

### CODE REVIEW

**Comment by JoshRosen** [comment]
In order for this to actually test the right thing you're going to need to also update the Travis build matrix at https://github.com/databricks/spark-avro/blob/branch-3.1/.travis.yml#L13

**Comment by bdrillard** [comment]
I'd like to see this pull request merged, it's a prerequisite to a pull request for Avro encoders (see [#169](https://github.com/databricks/spark-avro/issues/169))

**Comment by andrioni** [comment]
Any idea on when this is going to get merged/a new release will be made?

**Comment by elyast** [comment]
+1

**Comment by carlos-eduardo-gb** [comment]
+1

**Comment by schwartzmx** [comment]
👍

**Comment by alexander-branevskiy** [comment]
+1

**Comment by JoshRosen** [comment]
I'll merge this today. It's going to be a little while before I'll be able to push a release to Maven Central because this process is currently blocked by an infrastructure issue on our end.

**Comment by hardkap** [comment]
+1, Waiting for this to get in.

**Comment by JoshRosen** [comment]
It looks like it's possible to produce a single `spark-avro` binary artifact which is compatible with both Spark 2.0.x and 2.1.x. Thus I'm going to close this PR in favor of #212, which adds one additional commit to restore Spark 2.0.x compatibility. If my PR passes tests then I'll merge it and release version 3.2.0 of this library.

**Comment by JoshRosen** [comment]
Actually, I'll merge this now and layer the compatibility piece in a separate patch.

**Pull request closed without merging**
