### PR TITLE
Test for globbed paths support

### PR DESCRIPTION
**Pull request by vlyubin**

### CODE REVIEW

**Comment by aarondav** [comment]
LGTM. I wonder what happens if you do `src/*/*/{episodes.avro,episodes.avro}`.

**Comment by vlyubin** [comment]
@aarondav `src/*/*/{episodes.avro,episodes.avro}` works as well.

**Comment by aarondav** [comment]
But does it duplicate the data?

**Comment by vlyubin** [comment]
No, it doesn't (`collect()` still returns 8 entries). This is reasonable though, right? `src/*/*/*/{test.avro,test2.avro}` gets both of them as expected.

**Comment by aarondav** [comment]
Yup, 8 is what I would have expected, sounds goodl.

**Pull request merged**
