### PR TITLE
add support for DateType

### PR DESCRIPTION
**Pull request by nihed**
Hi, 
based on this issue https://github.com/databricks/spark-avro/issues/67
I create this pull request

### CODE REVIEW

**Comment by blrnw3** [comment]
This is a critical issue imo.  👍

**Comment by vlyubin** [comment]
Hey, I rebased your PR here - https://github.com/databricks/spark-avro/pull/209

**Comment by vlyubin** [comment]
@JoshRosen This seems to be good to merge.

**Comment by vlyubin** [comment]
Ok, I'll merge this as it has a unit test, and is relatively simple change that shouldn't break other things.

**Pull request closed without merging**
