### PR TITLE
Added differentiation of nested records with the same name

### PR DESCRIPTION
**Pull request by reyven**
by adding to each record definition a namespace definition consisting of a
dot-separated concatenation of the enclosing records' names.

This fixes https://github.com/databricks/spark-avro/issues/54

The implementation adheres to the Avro name/namespace specification
at https://avro.apache.org/docs/1.7.7/spec.html#Names
and uses the fullname definition (as opposed to seperate name and
namespace definition) to preserve union type resolution.

### CODE REVIEW

**Comment by JoshRosen** [comment]
This failed code style checks; please see the Travis output.

**Comment by JoshRosen** [comment]
Can you add a regression test for this bug?

**Comment by vlyubin** [comment]
Ping @reyven - it would be nice to merge this once we have a test.

**Comment by H4ml3t** [comment]
Any update? I'm stuck with this issues.

**Comment by dmitriy-svds** [comment]
Hello all,

It would be great to have this merged. I'm having the same issue.

Thanks!

**Comment by JoshRosen** [comment]
There's no way that we can safely merge this without tests. It would be great if someone could take over this PR to contribute tests for this feature.

**Comment by vlyubin** [comment]
Here's a simple test that can be added to AvroSuite:
```scala
  // Classes have to be defined outside of the test
  case class NestedBottom(id: Int, data: String)
  case class NestedMiddle(id: Int, data: NestedBottom)
  case class NestedTop(id: Int, data: NestedMiddle)

  test("saving avro that has nested records with the same name") {
    TestUtils.withTempDir { tempDir =>
      val df = TestSQLContext.createDataFrame(List(NestedTop(1, NestedMiddle(2, NestedBottom(3, "1")))))
      df.write.avro(s"$tempDir/duplicate_names/")
    }
  }
```

Unfortunately, it seems like the current solution doesn't resolve the issue, the test above fails with `UnresolvedUnionException` :(

**Comment by dotcomputercraft** [comment]
Hello all,  Can we merge this PR?

**Comment by lyubinetz** [comment]
@dotcomputercraft I don't think this really works.

https://github.com/databricks/spark-avro/pull/249 was just proposed and on the first glance it actually works!

**Comment by gengliangwang** [comment]
I think this issue will be resolved in #249 .
Close this PR since it doesn't work and there is no update.

**Pull request closed without merging**
