### PR TITLE
Add a note about using sbt assembly when using --jars

### PR DESCRIPTION
**Pull request by tyro89**
This might be a useful note to add to the readme. In my case sbt assembly greatly simplified using spark-avro on an emr cluster. Maybe the note could help others? :)

### CODE REVIEW

**Comment by marmbrus** [comment]
As an alternative, should we just suggest using `--packages` instead?

**Comment by tyro89** [comment]
@marmbrus :+1: that's much better. Would you say that `--packages` is the recommended way to link the jar vs `--jars`? I can update this section a little to mention both but put emphasis on `--packages`.

**Comment by marmbrus** [comment]
yeah, i think since `packages` always handles dependencies I would prefer it to `jars`.

**Comment by JoshRosen** [comment]
Given user confusion (see #64), we should update the docs to include `--packages` before 2.0.

**Comment by JoshRosen** [comment]
The README was updated to mention `--packages` in 7c66855d55a00ae8b7f0ff5f329028f0b9ec2b3e, so I'm going to mark this as resolved.

**Pull request closed without merging**
